services:
  

  backend:
    build: ./backend
    container_name: dineEase-backend
    ports:
      - 4001:4001
    environment:
      - PORT=4001
    env_file:
      - ./backend/.env


  frontend:
    build: ./frontend
    container_name: dineEase-frontend
    ports:
      - 80:80
    depends_on: 
      - backend